import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TermsConditions = () => {
  const navigate = useNavigate();

  return (
    <div className="max-w-4xl mx-auto py-8">
      <div className="mb-6 flex items-center">
        <button 
          onClick={() => navigate(-1)}
          className="flex items-center text-purple-700 hover:text-purple-900 transition-colors mr-4"
        >
          <ArrowLeft size={20} className="mr-1" />
          Back
        </button>
        <h1 className="text-3xl font-bold text-purple-900">Terms & Conditions</h1>
      </div>
      <div className="bg-white p-6 rounded-lg shadow mb-8">
        <p className="mb-4 text-gray-600 italic">Updated at 2023-04-01</p>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">General Terms</h2>
          <p className="mb-4">By accessing and placing an order with POSTWAND LLC (referred to as "postwand"), you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and postwand.</p>
          <p className="mb-4">Under no circumstances shall postwand team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if postwand team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</p>
          <p className="mb-4">postwand will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">License</h2>
          <p className="mb-4">postwand grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.</p>
          <p className="mb-4">These Terms & Conditions are a contract between you and postwand (referred to in these Terms & Conditions as "postwand", "us", "we" or "our"), the provider of the postwand website and the services accessible from the postwand website (which are collectively referred to in these Terms & Conditions as the "postwand Service").</p>
          <p className="mb-4">You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the postwand Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Definitions and key terms</h2>
          <p className="mb-4">To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
            <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to POSTWAND LLC, doing business as postwand, that is responsible for your information under this Terms & Conditions.</li>
            <li><strong>Country:</strong> where postwand or the owners/founders of postwand are based, in this case is Spain</li>
            <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit postwand and use the services.</li>
            <li><strong>Service:</strong> refers to the service provided by postwand as described in the relative terms (if available) and on this platform.</li>
            <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
            <li><strong>Website:</strong> postwand's site, which can be accessed via this URL: postwand.io</li>
            <li><strong>You:</strong> a person or entity that is registered with postwand to use the Services.</li>
          </ul>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Restrictions</h2>
          <p className="mb-4">You agree not to, and you will not permit others to:</p>
          <ul className="list-disc pl-6 mb-4 space-y-1">
            <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
            <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
            <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of postwand or its affiliates, partners, suppliers or the licensors of the website.</li>
          </ul>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Return and Refund Policy</h2>
          <p className="mb-4">Thanks for shopping at postwand. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.</p>
          <p className="mb-4">As with any shopping experience, there are terms and conditions that apply to transactions at postwand. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at postwand, you agree to the terms along with postwand's Privacy Policy.</p>
          <p className="mb-4">If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Your Suggestions</h2>
          <p className="mb-4">Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to postwand with respect to the website shall remain the sole and exclusive property of postwand.</p>
          <p className="mb-4">postwand shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Your Consent</h2>
          <p className="mb-4">We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Links to Other Websites</h2>
          <p className="mb-4">This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by postwand. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Cookies</h2>
          <p className="mb-4">postwand uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Changes To Our Terms & Conditions</h2>
          <p className="mb-4">You acknowledge and agree that postwand may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform postwand when you stop using the Service. You acknowledge and agree that if postwand disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.</p>
          <p className="mb-4">If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Modifications to Our website</h2>
          <p className="mb-4">postwand reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Updates to Our website</h2>
          <p className="mb-4">postwand may from time to time provide enhancements or improvements to the features/ functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").</p>
          <p className="mb-4">Updates may modify or delete certain features and/or functionalities of the website. You agree that postwand has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website to you.</p>
          <p className="mb-4">You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms and conditions of this Agreement.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3 text-purple-800">Contact Us</h2>
          <p className="mb-4">Don't hesitate to contact us if you have any questions.</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Via Email: <a href="mailto:albert@postwand.io" className="text-purple-600 hover:underline">albert@postwand.io</a></li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default TermsConditions; 